In [1]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [2]:
min_max = np.random.random((10,10))
min_ = min_max.min()
print(min_)
max_ = min_max.max()
print(max_)

0.0026280299441726607
0.9943581290456939


**15. Create a 2d array with 1 on the border and 0 inside**

In [3]:
a=np.full((10,10),1)
a[1:-1, 1:-1] = 0 # from 1 to end row,from 1 to end column
# a[1,1]=1
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
