In [1]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [6]:
A = np.random.random((3,2))
# A = A [[-1],:] 
# print(A)
# A[[-1],:] = A[[0],:]
print('Original array:','\n',A,'\n')
A[:,::-1]
print('After swap:','\n',A[::-1,:])

Original array: 
 [[0.77829041 0.80500119]
 [0.47204096 0.31876268]
 [0.013468   0.31567173]] 

After swap: 
 [[0.013468   0.31567173]
 [0.47204096 0.31876268]
 [0.77829041 0.80500119]]


**75. How to compute averages using a sliding window over an array?**

In [7]:
a = [1,2,3,4,5]
avg = np.cumsum(a)
print(avg)
avarages = []
for i in range(len(a)):
    print(i)
    avarages.append(avg[i]//(i+1)) 
print(avarages)

[ 1  3  6 10 15]
0
1
2
3
4
[1, 1, 2, 2, 3]
